version: '3'
services:
  auth_postgres:
    image: postgres:latest
    container_name: auth_postgres_container
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSRGRES_DB
    restart: always
    expose:
      - "5432"

  auth_mongo: 
    image: mongo
    container_name: auth_mongo_container
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - ./docker/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  auth:
    build: 
      context: .
      dockerfile: ./docker/auth/Dockerfile
    container_name: auth_container
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - SECRET_KEY=tplogistic
      - ALGORITHM=HS256
    depends_on:
      - auth_postgres
    ports:
      - 8000:80
    restart: on-failure

networks:
  app_network:
    name: app_network
    driver: bridge