version: '3'
services:
  auth_postgres:
    image: postgres:latest
    container_name: auth_postgres_container
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSRGRES_DB
    restart: always
    profiles:
      - sql
    expose:
      - "5432"

  auth_mongo: 
    image: mongo
    container_name: mongo_container
    networks:
      - app_network
    ports:
      - 27017:27017
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - ./docker/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    profiles:
      - dev

  auth:
    image: www.thinhlh.com/auth_service
    container_name: auth_container
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - SECRET_KEY
      - ALGORITHM
      - MONGO_INITDB_HOST
      - MONGO_INITDB_PORT
      - MONGO_INITDB_DATABASE
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    depends_on:
      - auth_postgres
    ports:
      - 8000:80
    networks:
      - app_network
    restart: on-failure

networks:
  app_network:
    name: app_network
    driver: bridge
    external: true